spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://remotemysql.com:3306/Gloqiiqfyo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: Gloqiiqfyo
    password: pclIkHqoVc

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
